pipeline {
    agent any

    stages {
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('quest-boot') {
                    sh 'mvn -version'
                    sh 'mvn package'
                }
            }
        }


        stage('Analyse Sonar') {

            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('quest-boot') {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=quest-boot -Dsonar.projectName='quest-boot'"
                    }
                }
            }
        }
    
        stage('Docker Build') {
            steps {
                dir('quest-boot') {
                    sh 'docker build -t ajc/quest:boot .'
                }
            }
        }

        // stage('Docker Deploy') {
        //     steps {
        //         dir('DOCKER/commandes/compose/quest') {
        //             sh 'docker compose up -d --build angular'
        //         }
        //     }
        // }
    }
}
