pipeline {
    agent any

    stage('Analyse Sonar') {
    agent {
        docker {
            image 'maven:3.9.11-eclipse-temurin-21'
            args '''
                -v $HOME/.m2:/root/.m2:z
                -u root
                --network devops
            '''
            reuseNode true
        }
    }
    steps {
        dir('quest-boot') {

          sh 'mvn -version'
          sh 'mvn package'


            withSonarQubeEnv('SonarQube') {
                sh 'mvn sonar:sonar -Dsonar.projectKey=quest-boot -Dsonar.projectName=quest-boot'
            }
        }
    }
}




        stage('Docker Build') {
            steps {
                dir('quest-boot') {
                    sh 'docker build -t ajc/quest:boot .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {
                dir('DOCKER/commandes/compose/quest') {
                    sh 'docker compose up -d'
                }
            }
        }
    
}
