
quarkus.http.host = 0.0.0.0
# quarkus.http.port = 8081

# Activer les loggers pour fr.formation
quarkus.log.category."fr.formation".level = DEBUG

# Configuration JPA/HIBERNATE avec Panache
quarkus.datasource.db-kind = mysql
quarkus.datasource.jdbc.url = jdbc:mysql://ajc-dev-mysql:3306/formation_quarkus
quarkus.datasource.username = root
quarkus.datasource.password =

# -- Permet de générer les tables, colonnes, etc.
quarkus.hibernate-orm.database.generation = update

# -- Permet d'afficher les requêtes SQL en log
quarkus.hibernate-orm.log.sql = true

# # Configuration des utilisateurs en mémoire

# # Activer les users en mémoire
# quarkus.security.users.embedded.enabled = true

# # Activer les mots de passe en clair
# quarkus.security.users.embedded.plain-text = true

# # Utilisateur "admin"
# quarkus.security.users.embedded.users.admin = 123456
# quarkus.security.users.embedded.roles.admin = admin

# # Utilisateur "user1"
# quarkus.security.users.embedded.users.user1 = 123456
# quarkus.security.users.embedded.roles.user1 = user

# Configuration des autorisations
quarkus.http.auth.permission.produit-all.paths = /produit
quarkus.http.auth.permission.produit-all.policy = permit
quarkus.http.auth.permission.produit-all.methods = GET

quarkus.http.auth.policy.role-policy-user.roles-allowed = user
quarkus.http.auth.policy.role-policy-admin.roles-allowed = admin

quarkus.http.auth.permission.produit-user.paths = /produit/*
quarkus.http.auth.permission.produit-user.policy = role-policy-user
quarkus.http.auth.permission.produit-user.methods = GET

quarkus.http.auth.permission.produit-admin.paths = /produit, /produit/*
quarkus.http.auth.permission.produit-admin.policy = role-policy-admin
quarkus.http.auth.permission.produit-admin.methods = POST,PUT,DELETE

# quarkus.http.auth.permission.produit-admin-post.paths = /produit
# quarkus.http.auth.permission.produit-admin-post.policy = role-policy-admin
# quarkus.http.auth.permission.produit-admin-post.methods = POST



